=head1 NAME

AdminEmailTest

=head1 DESCRIPTION

This is useful for every demo instance with no email account defined and where the tester
has no access to the commandline to run I<otrs.PostMaster.pl>.

=head1 REPOSITORY AND BUGTRACKER

The code repository and a bugtracker is available at
L<http://github.com/reneeb/otrs-AdminEmailTest>.

=head1 AUTHOR AND LICENSE

This addon is licensed under the terms of AGPL 3.

Renee Baecker, C<< <info@perl-services.de> >>
